export const CREATE_AUTHOR = "CREATE_AUTHOR";
export const LOAD_STUDENT_SUCCESS = "LOAD_STUDENT_SUCCESS";
export const VERIFY_STUDENT_SUCCESS = "VERIFY_STUDENT_SUCCESS";
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
// export const DELETE_COURSE_OPTIMISTIC = "DELETE_COURSE_OPTIMISTIC";
export const ADMINISTRATOR_SIGNIN_SUCCESS = "ADMINISTRATOR_SIGNIN_SUCCESS";
export const VERIFY_ADMIN_SUCCESS = "VERIFY_ADMIN_SUCCESS";
export const GET_EXAMS_SUCCESS = "GET_EXAMS_SUCCESS";
export const CREATE_EXAM_SUCCESS = "CREATE_EXAM_SUCCESS";
export const GET_PIN_SUCCESS = "GET_PIN_SUCCESS";
export const CREATE_PIN_SUCCESS = "CREATE_PIN_SUCCESS";
export const GET_ADMINISTRATOR_SUCCESS = "GET_ADMINISTRATOR_SUCCESS";
export const CREATE_ADMINISTRATOR_SUCCESS = "CREATE_ADMINISTRATOR_SUCCESS";

export const DELETE_ADMINISTRATOR_OPTIMISTIC = "DELETE_ADMINISTRATOR_OPTIMISTIC";

//  For students
export const LOAD_EXAMINATION_SUCCESS= "LOAD_EXAMINATION_SUCCESS";
